// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthHandler creates a new instance of MockAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthHandler {
	mock := &MockAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthHandler is an autogenerated mock type for the AuthHandler type
type MockAuthHandler struct {
	mock.Mock
}

type MockAuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthHandler) EXPECT() *MockAuthHandler_Expecter {
	return &MockAuthHandler_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) CreateAccount(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAuthHandler_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) CreateAccount(c interface{}) *MockAuthHandler_CreateAccount_Call {
	return &MockAuthHandler_CreateAccount_Call{Call: _e.mock.On("CreateAccount", c)}
}

func (_c *MockAuthHandler_CreateAccount_Call) Run(run func(c echo.Context)) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_CreateAccount_Call) Return(err error) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_CreateAccount_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) DeleteUser(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthHandler_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) DeleteUser(c interface{}) *MockAuthHandler_DeleteUser_Call {
	return &MockAuthHandler_DeleteUser_Call{Call: _e.mock.On("DeleteUser", c)}
}

func (_c *MockAuthHandler_DeleteUser_Call) Run(run func(c echo.Context)) *MockAuthHandler_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_DeleteUser_Call) Return(err error) *MockAuthHandler_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_DeleteUser_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) Login(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) Login(c interface{}) *MockAuthHandler_Login_Call {
	return &MockAuthHandler_Login_Call{Call: _e.mock.On("Login", c)}
}

func (_c *MockAuthHandler_Login_Call) Run(run func(c echo.Context)) *MockAuthHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_Login_Call) Return(err error) *MockAuthHandler_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_Login_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) Logout(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthHandler_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) Logout(c interface{}) *MockAuthHandler_Logout_Call {
	return &MockAuthHandler_Logout_Call{Call: _e.mock.On("Logout", c)}
}

func (_c *MockAuthHandler_Logout_Call) Run(run func(c echo.Context)) *MockAuthHandler_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_Logout_Call) Return(err error) *MockAuthHandler_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_Logout_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) Me(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockAuthHandler_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) Me(c interface{}) *MockAuthHandler_Me_Call {
	return &MockAuthHandler_Me_Call{Call: _e.mock.On("Me", c)}
}

func (_c *MockAuthHandler_Me_Call) Run(run func(c echo.Context)) *MockAuthHandler_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_Me_Call) Return(err error) *MockAuthHandler_Me_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_Me_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_Me_Call {
	_c.Call.Return(run)
	return _c
}

// ReactivateAccount provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) ReactivateAccount(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ReactivateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_ReactivateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReactivateAccount'
type MockAuthHandler_ReactivateAccount_Call struct {
	*mock.Call
}

// ReactivateAccount is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) ReactivateAccount(c interface{}) *MockAuthHandler_ReactivateAccount_Call {
	return &MockAuthHandler_ReactivateAccount_Call{Call: _e.mock.On("ReactivateAccount", c)}
}

func (_c *MockAuthHandler_ReactivateAccount_Call) Run(run func(c echo.Context)) *MockAuthHandler_ReactivateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_ReactivateAccount_Call) Return(err error) *MockAuthHandler_ReactivateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_ReactivateAccount_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_ReactivateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) UpdatePassword(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAuthHandler_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) UpdatePassword(c interface{}) *MockAuthHandler_UpdatePassword_Call {
	return &MockAuthHandler_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", c)}
}

func (_c *MockAuthHandler_UpdatePassword_Call) Run(run func(c echo.Context)) *MockAuthHandler_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_UpdatePassword_Call) Return(err error) *MockAuthHandler_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_UpdatePassword_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) UpdateUser(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAuthHandler_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) UpdateUser(c interface{}) *MockAuthHandler_UpdateUser_Call {
	return &MockAuthHandler_UpdateUser_Call{Call: _e.mock.On("UpdateUser", c)}
}

func (_c *MockAuthHandler_UpdateUser_Call) Run(run func(c echo.Context)) *MockAuthHandler_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_UpdateUser_Call) Return(err error) *MockAuthHandler_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_UpdateUser_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
