// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/SergioLNeves/auth-session/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateUser(ctx context.Context, user *domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockAuthRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockAuthRepository_CreateUser_Call {
	return &MockAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockAuthRepository_CreateUser_Call) Run(run func(ctx context.Context, user *domain.User)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) Return(err error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeactivatedUsers provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) DeleteDeactivatedUsers(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeactivatedUsers")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_DeleteDeactivatedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeactivatedUsers'
type MockAuthRepository_DeleteDeactivatedUsers_Call struct {
	*mock.Call
}

// DeleteDeactivatedUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthRepository_Expecter) DeleteDeactivatedUsers(ctx interface{}) *MockAuthRepository_DeleteDeactivatedUsers_Call {
	return &MockAuthRepository_DeleteDeactivatedUsers_Call{Call: _e.mock.On("DeleteDeactivatedUsers", ctx)}
}

func (_c *MockAuthRepository_DeleteDeactivatedUsers_Call) Run(run func(ctx context.Context)) *MockAuthRepository_DeleteDeactivatedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthRepository_DeleteDeactivatedUsers_Call) Return(n int64, err error) *MockAuthRepository_DeleteDeactivatedUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuthRepository_DeleteDeactivatedUsers_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockAuthRepository_DeleteDeactivatedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockAuthRepository_DeleteUser_Call {
	return &MockAuthRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockAuthRepository_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_DeleteUser_Call) Return(err error) *MockAuthRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockAuthRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockAuthRepository_FindUserByEmail_Call {
	return &MockAuthRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockAuthRepository_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_FindUserByEmail_Call) Return(user *domain.User, err error) *MockAuthRepository_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockAuthRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) FindUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockAuthRepository_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepository_Expecter) FindUserByID(ctx interface{}, id interface{}) *MockAuthRepository_FindUserByID_Call {
	return &MockAuthRepository_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, id)}
}

func (_c *MockAuthRepository_FindUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepository_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_FindUserByID_Call) Return(user *domain.User, err error) *MockAuthRepository_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.User, error)) *MockAuthRepository_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAuthRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockAuthRepository_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockAuthRepository_UpdateUser_Call {
	return &MockAuthRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockAuthRepository_UpdateUser_Call) Run(run func(ctx context.Context, user *domain.User)) *MockAuthRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_UpdateUser_Call) Return(err error) *MockAuthRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) error) *MockAuthRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
