// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/SergioLNeves/auth-session/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockAuthService
func (_mock *MockAuthService) CreateAccount(ctx context.Context, req domain.CreateAccountRequest) (*domain.AuthResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *domain.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateAccountRequest) (*domain.AuthResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateAccountRequest) *domain.AuthResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateAccountRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAuthService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateAccountRequest
func (_e *MockAuthService_Expecter) CreateAccount(ctx interface{}, req interface{}) *MockAuthService_CreateAccount_Call {
	return &MockAuthService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, req)}
}

func (_c *MockAuthService_CreateAccount_Call) Run(run func(ctx context.Context, req domain.CreateAccountRequest)) *MockAuthService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateAccountRequest
		if args[1] != nil {
			arg1 = args[1].(domain.CreateAccountRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_CreateAccount_Call) Return(authResponse *domain.AuthResponse, err error) *MockAuthService_CreateAccount_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *MockAuthService_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, req domain.CreateAccountRequest) (*domain.AuthResponse, error)) *MockAuthService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) DeleteUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) DeleteUser(ctx interface{}, userID interface{}) *MockAuthService_DeleteUser_Call {
	return &MockAuthService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockAuthService_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_DeleteUser_Call) Return(err error) *MockAuthService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockAuthService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, req domain.LoginRequest) (*domain.AuthResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) (*domain.AuthResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) *domain.AuthResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.LoginRequest
func (_e *MockAuthService_Expecter) Login(ctx interface{}, req interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, req domain.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(domain.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(authResponse *domain.AuthResponse, err error) *MockAuthService_Login_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, req domain.LoginRequest) (*domain.AuthResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, sessionID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// ReactivateAccount provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ReactivateAccount(ctx context.Context, req domain.LoginRequest) (*domain.AuthResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReactivateAccount")
	}

	var r0 *domain.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) (*domain.AuthResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) *domain.AuthResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ReactivateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReactivateAccount'
type MockAuthService_ReactivateAccount_Call struct {
	*mock.Call
}

// ReactivateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.LoginRequest
func (_e *MockAuthService_Expecter) ReactivateAccount(ctx interface{}, req interface{}) *MockAuthService_ReactivateAccount_Call {
	return &MockAuthService_ReactivateAccount_Call{Call: _e.mock.On("ReactivateAccount", ctx, req)}
}

func (_c *MockAuthService_ReactivateAccount_Call) Run(run func(ctx context.Context, req domain.LoginRequest)) *MockAuthService_ReactivateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(domain.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ReactivateAccount_Call) Return(authResponse *domain.AuthResponse, err error) *MockAuthService_ReactivateAccount_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *MockAuthService_ReactivateAccount_Call) RunAndReturn(run func(ctx context.Context, req domain.LoginRequest) (*domain.AuthResponse, error)) *MockAuthService_ReactivateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) UpdatePassword(ctx context.Context, userID string, req domain.UpdatePasswordRequest) error {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UpdatePasswordRequest) error); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAuthService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req domain.UpdatePasswordRequest
func (_e *MockAuthService_Expecter) UpdatePassword(ctx interface{}, userID interface{}, req interface{}) *MockAuthService_UpdatePassword_Call {
	return &MockAuthService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, req)}
}

func (_c *MockAuthService_UpdatePassword_Call) Run(run func(ctx context.Context, userID string, req domain.UpdatePasswordRequest)) *MockAuthService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UpdatePasswordRequest
		if args[2] != nil {
			arg2 = args[2].(domain.UpdatePasswordRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_UpdatePassword_Call) Return(err error) *MockAuthService_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID string, req domain.UpdatePasswordRequest) error) *MockAuthService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) UpdateUser(ctx context.Context, userID string, req domain.UpdateUserRequest) (*domain.UserResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *domain.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UpdateUserRequest) (*domain.UserResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UpdateUserRequest) *domain.UserResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAuthService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req domain.UpdateUserRequest
func (_e *MockAuthService_Expecter) UpdateUser(ctx interface{}, userID interface{}, req interface{}) *MockAuthService_UpdateUser_Call {
	return &MockAuthService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, req)}
}

func (_c *MockAuthService_UpdateUser_Call) Run(run func(ctx context.Context, userID string, req domain.UpdateUserRequest)) *MockAuthService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UpdateUserRequest
		if args[2] != nil {
			arg2 = args[2].(domain.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_UpdateUser_Call) Return(userResponse *domain.UserResponse, err error) *MockAuthService_UpdateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockAuthService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, userID string, req domain.UpdateUserRequest) (*domain.UserResponse, error)) *MockAuthService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
