// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthCheckHandler creates a new instance of MockHealthCheckHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckHandler {
	mock := &MockHealthCheckHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthCheckHandler is an autogenerated mock type for the HealthCheckHandler type
type MockHealthCheckHandler struct {
	mock.Mock
}

type MockHealthCheckHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckHandler) EXPECT() *MockHealthCheckHandler_Expecter {
	return &MockHealthCheckHandler_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockHealthCheckHandler
func (_mock *MockHealthCheckHandler) Check(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthCheckHandler_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockHealthCheckHandler_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockHealthCheckHandler_Expecter) Check(ctx interface{}) *MockHealthCheckHandler_Check_Call {
	return &MockHealthCheckHandler_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockHealthCheckHandler_Check_Call) Run(run func(ctx echo.Context)) *MockHealthCheckHandler_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheckHandler_Check_Call) Return(err error) *MockHealthCheckHandler_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthCheckHandler_Check_Call) RunAndReturn(run func(ctx echo.Context) error) *MockHealthCheckHandler_Check_Call {
	_c.Call.Return(run)
	return _c
}
