// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/SergioLNeves/auth-session/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthCheckerService creates a new instance of MockHealthCheckerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckerService {
	mock := &MockHealthCheckerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthCheckerService is an autogenerated mock type for the HealthCheckerService type
type MockHealthCheckerService struct {
	mock.Mock
}

type MockHealthCheckerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckerService) EXPECT() *MockHealthCheckerService_Expecter {
	return &MockHealthCheckerService_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockHealthCheckerService
func (_mock *MockHealthCheckerService) Check() (domain.HealthCheck, []error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 domain.HealthCheck
	var r1 []error
	if returnFunc, ok := ret.Get(0).(func() (domain.HealthCheck, []error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() domain.HealthCheck); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.HealthCheck)
	}
	if returnFunc, ok := ret.Get(1).(func() []error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}
	return r0, r1
}

// MockHealthCheckerService_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockHealthCheckerService_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
func (_e *MockHealthCheckerService_Expecter) Check() *MockHealthCheckerService_Check_Call {
	return &MockHealthCheckerService_Check_Call{Call: _e.mock.On("Check")}
}

func (_c *MockHealthCheckerService_Check_Call) Run(run func()) *MockHealthCheckerService_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckerService_Check_Call) Return(healthCheck domain.HealthCheck, errs []error) *MockHealthCheckerService_Check_Call {
	_c.Call.Return(healthCheck, errs)
	return _c
}

func (_c *MockHealthCheckerService_Check_Call) RunAndReturn(run func() (domain.HealthCheck, []error)) *MockHealthCheckerService_Check_Call {
	_c.Call.Return(run)
	return _c
}
