// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"time"

	"github.com/SergioLNeves/auth-session/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Session
		if args[1] != nil {
			arg1 = args[1].(*domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(err error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session *domain.Session) error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockSessionRepository_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) DeleteExpiredSessions(ctx interface{}) *MockSessionRepository_DeleteExpiredSessions_Call {
	return &MockSessionRepository_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions", ctx)}
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Run(run func(ctx context.Context)) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Return(n int64, err error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteSession(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSessionRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_DeleteSession_Call {
	return &MockSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) Return(session *domain.Session, err error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeleteSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserID'
type MockSessionRepository_DeleteSessionsByUserID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepository_Expecter) DeleteSessionsByUserID(ctx interface{}, userID interface{}) *MockSessionRepository_DeleteSessionsByUserID_Call {
	return &MockSessionRepository_DeleteSessionsByUserID_Call{Call: _e.mock.On("DeleteSessionsByUserID", ctx, userID)}
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) Return(err error) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindSessionByID(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByID")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByID'
type MockSessionRepository_FindSessionByID_Call struct {
	*mock.Call
}

// FindSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSessionRepository_Expecter) FindSessionByID(ctx interface{}, sessionID interface{}) *MockSessionRepository_FindSessionByID_Call {
	return &MockSessionRepository_FindSessionByID_Call{Call: _e.mock.On("FindSessionByID", ctx, sessionID)}
}

func (_c *MockSessionRepository_FindSessionByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindSessionByID_Call) Return(session *domain.Session, err error) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error)) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionExpiry provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateSessionExpiry(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionExpiry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateSessionExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionExpiry'
type MockSessionRepository_UpdateSessionExpiry_Call struct {
	*mock.Call
}

// UpdateSessionExpiry is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateSessionExpiry(ctx interface{}, sessionID interface{}, expiresAt interface{}) *MockSessionRepository_UpdateSessionExpiry_Call {
	return &MockSessionRepository_UpdateSessionExpiry_Call{Call: _e.mock.On("UpdateSessionExpiry", ctx, sessionID, expiresAt)}
}

func (_c *MockSessionRepository_UpdateSessionExpiry_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time)) *MockSessionRepository_UpdateSessionExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateSessionExpiry_Call) Return(err error) *MockSessionRepository_UpdateSessionExpiry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateSessionExpiry_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time) error) *MockSessionRepository_UpdateSessionExpiry_Call {
	_c.Call.Return(run)
	return _c
}
