// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockStorage
func (_mock *MockStorage) FindByEmail(ctx context.Context, table string, email string, dest any) error {
	ret := _mock.Called(ctx, table, email, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = returnFunc(ctx, table, email, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockStorage_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - email string
//   - dest any
func (_e *MockStorage_Expecter) FindByEmail(ctx interface{}, table interface{}, email interface{}, dest interface{}) *MockStorage_FindByEmail_Call {
	return &MockStorage_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, table, email, dest)}
}

func (_c *MockStorage_FindByEmail_Call) Run(run func(ctx context.Context, table string, email string, dest any)) *MockStorage_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_FindByEmail_Call) Return(err error) *MockStorage_FindByEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, table string, email string, dest any) error) *MockStorage_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockStorage
func (_mock *MockStorage) FindByID(ctx context.Context, table string, id any, dest any) error {
	ret := _mock.Called(ctx, table, id, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, table, id, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStorage_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - id any
//   - dest any
func (_e *MockStorage_Expecter) FindByID(ctx interface{}, table interface{}, id interface{}, dest interface{}) *MockStorage_FindByID_Call {
	return &MockStorage_FindByID_Call{Call: _e.mock.On("FindByID", ctx, table, id, dest)}
}

func (_c *MockStorage_FindByID_Call) Run(run func(ctx context.Context, table string, id any, dest any)) *MockStorage_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_FindByID_Call) Return(err error) *MockStorage_FindByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_FindByID_Call) RunAndReturn(run func(ctx context.Context, table string, id any, dest any) error) *MockStorage_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndDelete provides a mock function for the type MockStorage
func (_mock *MockStorage) FindOneAndDelete(ctx context.Context, table string, id any, dest any) error {
	ret := _mock.Called(ctx, table, id, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, table, id, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_FindOneAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndDelete'
type MockStorage_FindOneAndDelete_Call struct {
	*mock.Call
}

// FindOneAndDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - id any
//   - dest any
func (_e *MockStorage_Expecter) FindOneAndDelete(ctx interface{}, table interface{}, id interface{}, dest interface{}) *MockStorage_FindOneAndDelete_Call {
	return &MockStorage_FindOneAndDelete_Call{Call: _e.mock.On("FindOneAndDelete", ctx, table, id, dest)}
}

func (_c *MockStorage_FindOneAndDelete_Call) Run(run func(ctx context.Context, table string, id any, dest any)) *MockStorage_FindOneAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_FindOneAndDelete_Call) Return(err error) *MockStorage_FindOneAndDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_FindOneAndDelete_Call) RunAndReturn(run func(ctx context.Context, table string, id any, dest any) error) *MockStorage_FindOneAndDelete_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type MockStorage
func (_mock *MockStorage) GetDB() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockStorage_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type MockStorage_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GetDB() *MockStorage_GetDB_Call {
	return &MockStorage_GetDB_Call{Call: _e.mock.On("GetDB")}
}

func (_c *MockStorage_GetDB_Call) Run(run func()) *MockStorage_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GetDB_Call) Return(v any) *MockStorage_GetDB_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStorage_GetDB_Call) RunAndReturn(run func() any) *MockStorage_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockStorage
func (_mock *MockStorage) Insert(ctx context.Context, table string, data any) error {
	ret := _mock.Called(ctx, table, data)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, table, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockStorage_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - data any
func (_e *MockStorage_Expecter) Insert(ctx interface{}, table interface{}, data interface{}) *MockStorage_Insert_Call {
	return &MockStorage_Insert_Call{Call: _e.mock.On("Insert", ctx, table, data)}
}

func (_c *MockStorage_Insert_Call) Run(run func(ctx context.Context, table string, data any)) *MockStorage_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Insert_Call) Return(err error) *MockStorage_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Insert_Call) RunAndReturn(run func(ctx context.Context, table string, data any) error) *MockStorage_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Ping(ctx interface{}) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorage_Ping_Call) Run(run func(ctx context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorage
func (_mock *MockStorage) Update(ctx context.Context, table string, data any) error {
	ret := _mock.Called(ctx, table, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, table, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - data any
func (_e *MockStorage_Expecter) Update(ctx interface{}, table interface{}, data interface{}) *MockStorage_Update_Call {
	return &MockStorage_Update_Call{Call: _e.mock.On("Update", ctx, table, data)}
}

func (_c *MockStorage_Update_Call) Run(run func(ctx context.Context, table string, data any)) *MockStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Update_Call) Return(err error) *MockStorage_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Update_Call) RunAndReturn(run func(ctx context.Context, table string, data any) error) *MockStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}
