// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/SergioLNeves/auth-session/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateAccessToken(sessionID string) (string, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - sessionID string
func (_e *MockTokenProvider_Expecter) GenerateAccessToken(sessionID interface{}) *MockTokenProvider_GenerateAccessToken_Call {
	return &MockTokenProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", sessionID)}
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Run(run func(sessionID string)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Return(s string, err error) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) RunAndReturn(run func(sessionID string) (string, error)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateRefreshToken(userID string, sessionID string) (string, error) {
	ret := _mock.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenProvider_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - userID string
//   - sessionID string
func (_e *MockTokenProvider_Expecter) GenerateRefreshToken(userID interface{}, sessionID interface{}) *MockTokenProvider_GenerateRefreshToken_Call {
	return &MockTokenProvider_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", userID, sessionID)}
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) Run(run func(userID string, sessionID string)) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) RunAndReturn(run func(userID string, sessionID string) (string, error)) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseAccessToken(tokenString string) (*domain.AccessTokenClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *domain.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.AccessTokenClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.AccessTokenClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockTokenProvider_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenProvider_Expecter) ParseAccessToken(tokenString interface{}) *MockTokenProvider_ParseAccessToken_Call {
	return &MockTokenProvider_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", tokenString)}
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Run(run func(tokenString string)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Return(accessTokenClaims *domain.AccessTokenClaims, err error) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) RunAndReturn(run func(tokenString string) (*domain.AccessTokenClaims, error)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseRefreshToken(tokenString string) (*domain.RefreshTokenClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *domain.RefreshTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.RefreshTokenClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.RefreshTokenClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockTokenProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenProvider_Expecter) ParseRefreshToken(tokenString interface{}) *MockTokenProvider_ParseRefreshToken_Call {
	return &MockTokenProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", tokenString)}
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Run(run func(tokenString string)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Return(refreshTokenClaims *domain.RefreshTokenClaims, err error) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(refreshTokenClaims, err)
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) RunAndReturn(run func(tokenString string) (*domain.RefreshTokenClaims, error)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
