version: "2"
run:
  go: "1.25"
linters:
  enable:
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: receiver-naming
        - name: increment-decrement
        - name: error-naming
        - name: context-as-argument
        - name: dot-imports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - module github.com/SergioLNeves/migos
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
